name: 'Deploy a service to Wonderland 2'
description: 'Deploy a service to Wonderland 2'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  token:
    description: 'A GitHub token to use with wonderland'
    required: true
  bastion_key:
    description: 'Ssh key for authentication in the bastion host'
    deprecationMessage: 'Specifying a bastion_key is no longer needed.'
    required: false
  workspace:
    required: false
    description: 'The wonderland environment to deploy your application to (prod|stage)'
    default: 'prod'
    deprecationMessage: "Warning: 'workspace' parameter is deprecated please use 'environment' instead"
  environment:
    required: false
    description: 'The wonderland environment to deploy your application to (prod|stage)'
    default: 'prod'
  wonderland_manifest:
    required: false
    description: 'The Wonderland 2 manifest file'
    default: 'wonderland2.yaml'
  timeout:
    required: false
    description: 'Maximum time to wait for the deployment to become available'
    default: '10m'
  delete:
    required: false
    description: 'Delete the service instead of deploying it'
    default: 'false'
  cli_version:
    required: false
    description: 'The Wonderland 2 CLI version to use'
    default: 'v0.13.0'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.environment }}
    - ${{ inputs.wonderland_manifest }}
    - ${{ inputs.timeout }}
    - ${{ inputs.delete }}
    - ${{ inputs.workspace }}
    - ${{ inputs.cli_version }}
